version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build-linux:
    docker:
      - image: cimg/python:3.8  # Use an image with the required Python version
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run Tests
          command: pytest

  build-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            choco install python --version=3.8.0 --allow-downgrade -y
      - run:
          name: Install Dependencies and Run Tests
          command: |
            python -m pip install -r requirements.txt
            python -m pip install pytest
            python -m pytest

  build-macos:
    macos:
      xcode: "14.2.0"  # Specify the Xcode version here
    resource_class: macos.m1.medium.gen1  # Specify the resource class here
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            brew install python@3.8
            echo 'export PATH="/usr/local/opt/python@3.8/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Install Dependencies and Run Tests
          command: |
            python3 -m pip install -r requirements.txt
            python3 -m pip install pytest
            python3 -m pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-linux
      - build-windows
      - build-macos
