version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build-linux:
    parameters:
      python-version:
        type: string
    docker:
      - image: cimg/python:<< parameters.python-version >>  # Use an image with the required Python version
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run Tests
          command: pytest

  build-windows:
    parameters:
      python-version:
        type: string
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Uninstall Existing Python and Install Desired Version
          command: |
            choco uninstall python --allversions -y
            choco install python --version=<< parameters.python-version >> --allow-downgrade -y
      - run:
          name: Install Dependencies and Run Tests
          command: |
            python -m pip install -r requirements.txt
            python -m pip install pytest
            python -m pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-linux:
          matrix:
            parameters:
              python-version: ["3.8", "3.10", "3.12"]
      - build-windows:
          matrix:
            parameters:
              python-version: ["3.8", "3.10", "3.12"]
