version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build-linux:
    docker:
      - image: cimg/python:3.8  # Use an image with the required Python version
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
            pip install pytest
      - run:
          name: Run Tests
          command: pytest

  build-windows:
    executor:
      name: win/default
    steps:
      - checkout
      - run:
          name: Install Python
          command: |
            choco install python --version=3.8.0 --allow-downgrade -y
      - run:
          name: Install Dependencies and Run Tests
          command: |
            python -m pip install -r requirements.txt
            python -m pip install pytest
            python -m pytest

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-linux
      - build-windows
